<?php

/**
 * @file
 * Test module for Cart + Big Pipe.
 */
use Drupal\commerce_cart_big_pipe\Form\BigPipeAddToCartForm;

/**
 * Implements hook_module_implements_alter().
 */
function commerce_cart_big_pipe_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'entity_type_build') {
    // commerce_cart_big_pipe_entity_type_build() needs to run after
    // commerce_cart_entity_type_build().
    $group = $implementations['commerce_cart_big_pipe'];
    unset($implementations['commerce_cart_big_pipe']);
    $implementations['commerce_cart_big_pipe'] = $group;
  }
}

/**
 * Implements hook_entity_type_build().
 */
function commerce_cart_big_pipe_entity_type_build(array &$entity_types) {
  $entity_types['commerce_order_item']->setFormClass('add_to_cart', BigPipeAddToCartForm::class);
}
