<?php

/**
 * @file
 * Test module for Commerce Product.
 */

use Drupal\commerce_product\Entity\ProductInterface;
use Drupal\commerce_product\Entity\ProductVariationInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_access().
 */
function commerce_product_test_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  if ($entity instanceof ProductVariationInterface) {
    if ($operation == 'view') {
      return AccessResult::forbiddenIf(strpos($entity->getSku(), 'DENY') !== FALSE);
    }
  }
  if ($entity instanceof ProductInterface) {
    if ($operation == 'view') {
      return AccessResult::allowed();
    }
  }
  return AccessResult::neutral();
}
