<?php

/**
 * @file
 * Install hook for commerce_product_add_to_cart_variation_change test module.
 */

use Drupal\Core\Config\FileStorage;

/**
 * Implements hook_install().
 */
function commerce_product_add_to_cart_variation_change_install() {
  $config_storage = \Drupal::service('config.storage');
  $conf_sync_path = __DIR__ . '/sync';
  $conf_sync_storage = new FileStorage($conf_sync_path);

  foreach ($conf_sync_storage->listAll() as $config_name) {
    if ($config = $conf_sync_storage->read($config_name)) {
      $config_storage->write($config_name, $config);
    }
  }
}
